*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadorasimple;

/**
 *
 * @author Kevin
 */
public class Calculadora extends javax.swing.JFrame {
    int num1, num2;
    String signo;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pantalla = new javax.swing.JLabel();
        borrador = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        cero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pantalla.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pantalla.setForeground(new java.awt.Color(204, 255, 255));
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEtchedBorder()));
        pantalla.setOpaque(true);

        borrador.setBackground(new java.awt.Color(232, 231, 249));
        borrador.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        borrador.setText("c");
        borrador.setBorder(new javax.swing.border.MatteBorder(null));
        borrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borradorActionPerformed(evt);
            }
        });

        resta.setBackground(new java.awt.Color(232, 231, 249));
        resta.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        resta.setText("-");
        resta.setBorder(new javax.swing.border.MatteBorder(null));
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        dividir.setBackground(new java.awt.Color(232, 231, 249));
        dividir.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        dividir.setText("/");
        dividir.setBorder(new javax.swing.border.MatteBorder(null));
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });

        multiplicar.setBackground(new java.awt.Color(232, 231, 249));
        multiplicar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        multiplicar.setText("x");
        multiplicar.setBorder(new javax.swing.border.MatteBorder(null));
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });

        siete.setBackground(new java.awt.Color(232, 231, 249));
        siete.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        siete.setText("7");
        siete.setBorder(new javax.swing.border.MatteBorder(null));
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });

        ocho.setBackground(new java.awt.Color(232, 231, 249));
        ocho.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        ocho.setText("8");
        ocho.setBorder(new javax.swing.border.MatteBorder(null));
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        nueve.setBackground(new java.awt.Color(232, 231, 249));
        nueve.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        nueve.setText("9");
        nueve.setBorder(new javax.swing.border.MatteBorder(null));
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        suma.setBackground(new java.awt.Color(232, 231, 249));
        suma.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        suma.setText("+");
        suma.setBorder(new javax.swing.border.MatteBorder(null));
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        cuatro.setBackground(new java.awt.Color(232, 231, 249));
        cuatro.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        cuatro.setText("4");
        cuatro.setBorder(new javax.swing.border.MatteBorder(null));
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        cinco.setBackground(new java.awt.Color(232, 231, 249));
        cinco.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        cinco.setText("5");
        cinco.setBorder(new javax.swing.border.MatteBorder(null));
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        seis.setBackground(new java.awt.Color(232, 231, 249));
        seis.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        seis.setText("6");
        seis.setBorder(new javax.swing.border.MatteBorder(null));
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        uno.setBackground(new java.awt.Color(232, 231, 249));
        uno.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        uno.setText("1");
        uno.setBorder(new javax.swing.border.MatteBorder(null));
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        dos.setBackground(new java.awt.Color(232, 231, 249));
        dos.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        dos.setText("2");
        dos.setBorder(new javax.swing.border.MatteBorder(null));
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        tres.setBackground(new java.awt.Color(232, 231, 249));
        tres.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        tres.setText("3");
        tres.setBorder(new javax.swing.border.MatteBorder(null));
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        igual.setBackground(new java.awt.Color(232, 231, 249));
        igual.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        igual.setText("=");
        igual.setBorder(new javax.swing.border.MatteBorder(null));
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        cero.setBackground(new java.awt.Color(232, 231, 249));
        cero.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 16)); // NOI18N
        cero.setText("0");
        cero.setBorder(new javax.swing.border.MatteBorder(null));
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(borrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(siete, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cuatro, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(uno, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void borradorActionPerformed(java.awt.event.ActionEvent evt) {                                         
    pantalla.setText("");             // TODO add your handling code here:
    }                                        

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {                                     
    pantalla.setText(pantalla.getText()+"0");       // TODO add your handling code here:
    }                                    

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {                                    
    pantalla.setText(pantalla.getText()+"2");         // TODO add your handling code here:
    }                                   

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {                                    
    pantalla.setText(pantalla.getText()+"1");    // TODO add your handling code here:
    }                                   

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {                                     
    pantalla.setText(pantalla.getText()+"3");        // TODO add your handling code here:
    }                                    

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {                                       
    pantalla.setText(pantalla.getText()+"4");        // TODO add your handling code here:
    }                                      

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {                                      
    pantalla.setText(pantalla.getText()+"5");        // TODO add your handling code here:
    }                                     

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {                                     
    pantalla.setText(pantalla.getText()+"6");        // TODO add your handling code here:
    }                                    

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {                                      
    pantalla.setText(pantalla.getText()+"7");        // TODO add your handling code here:
    }                                     

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {                                     
    pantalla.setText(pantalla.getText()+"8");        // TODO add your handling code here:
    }                                    

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {                                      
    pantalla.setText(pantalla.getText()+"9");        // TODO add your handling code here:
    }                                     

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {                                        
    num1=Integer.parseInt(pantalla.getText());
    signo="/";
    pantalla.setText("");// TODO add your handling code here:
    }                                       

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {                                            
    num1=Integer.parseInt(pantalla.getText());
    signo="*";
    pantalla.setText("");        // TODO add your handling code here:
    }                                           

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {                                      
    num1=Integer.parseInt(pantalla.getText());
    signo="-";
    pantalla.setText("");        // TODO add your handling code here:
    }                                     

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {                                     
    num1=Integer.parseInt(pantalla.getText());
    signo="+";
    pantalla.setText("");        // TODO add your handling code here:
    }                                    

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {                                      
    num2=Integer.parseInt(pantalla.getText());
    
    switch (signo){
        case "+":
            pantalla.setText(Integer.toString(num1+num2));
            break;
        case "-":
            pantalla.setText(Integer.toString(num1-num2));
            break;
        case "*":
            pantalla.setText(Integer.toString(num1*num2));
            break;
        case "/":
            pantalla.setText(Integer.toString(num1/num2));
            break;
        }
    }                                     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton borrador;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton dividir;
    private javax.swing.JButton dos;
    private javax.swing.JButton igual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multiplicar;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JLabel pantalla;
    private javax.swing.JButton resta;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton suma;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration                   
}
